### ISSUE TITLE
侧边栏动画不统一

### ISSUE THREAD

**Issue by SOCK-MAGIC** [FunnySaltyFish/ComposeLoading#1]
进入关于动画有一个向上顶，之后从右侧进来，而其他的项都没有向上的动画

**Comment by FunnySaltyFish** [comment]
我看了半天才看明白，你是否想说译站。如果是的话，请移步译站的 [issue](https://github.com/FunnySaltyFish/FunnyTranslation/issues)

**Comment by SOCK-MAGIC** [comment]
@FunnySaltyFish 抱歉弄错项目了
